### ISSUE TITLE
Misplaced parameter in README example

### ISSUE THREAD

**Issue by taoroalin** [lyakaap/VAT-pytorch#4]
In the example in the README, the the model is passed to VATLoss.__init__, but it should be passed to VATLoss.forward() like,

VATLoss(model, xi=10.0, eps=1.0, ip=1)
vat_loss(data)

but it should be 

VATLoss(xi=10.0, eps=1.0, ip=1)
vat_loss(model, data)

thanks

**Comment by lyakaap** [comment]
Fixed. Thanks for pointing that.
